### ISSUE TITLE
Index length greater than 30 won't work with oracle

### ISSUE THREAD

**Issue by gokulnath** [charlotte-ruby/impressionist#186]
One of the indexs created by impressionist 'impressionable_type_message_index' is 33 characters which is not supported by oracle (http://stackoverflow.com/questions/1378133/why-are-oracle-table-column-index-names-limited-to-30-characters).

**Comment by gokulnath** [comment]
And when I manually reduce the length to 30 another error occurs
```
-- add_index("impressions", ["impressionable_type", "message", "impressionable_id"], {:name=>"impressionable_type_msg_index"})
rake aborted!
ActiveRecord::StatementInvalid: OCIError: ORA-02327: cannot create index on expression with datatype LOB: CREATE  INDEX "IMPRESSIONABLE_TYPE_MSG_INDEX" ON "IMPRESSIONS" ("IMPRESSIONABLE_TYPE", "MESSAGE", "IMPRESSIONABLE_ID") 
stmt.c:250:in oci8lib_220.so
/home/gokul/root/mobme/mpassbook-ubi-mpassbook-rails/vendor/bundle/ruby/2.2.0/gems/ruby-oci8-2.1.8/lib/oci8/cursor.rb:129:in `exec'
/home/gokul/root/mobme/mpassbook-ubi-mpassbook-rails/vendor/bundle/ruby/2.2.0/gems/ruby-oci8-2.1.8/lib/oci8/oci8.rb:278:in `exec_internal'
/home/gokul/root/mobme/mpassbook-ubi-mpassbook-rails/vendor/bundle/ruby/2.2.0/gems/ruby-oci8-2.1.8/lib/oci8/oci8.rb:269:in `exec'
/home/gokul/root/mobme/mpassbook-ubi-mpassbook-rails/vendor/cache/oracle-enhanced-6ca7870adaa1/lib/active_record/connection_adapters/oracle_enhanced_oci_connection.rb:431:in `exec'
/home/gokul/root/mobme/mpassbook-ubi-mpassbook-rails/vendor/cache/oracle-enhanced-6ca7870adaa1/lib/active_record/connection_adapters/oracle_enhanced_oci_connection.rb:90:in `exec'
/home/gokul/root/mobme/mpassbook-ubi-mpassbook-rails/vendor/cache/oracle-enhanced-6ca7870adaa1/lib/active_record/connection_adapters/oracle_enhanced_database_statements.rb:10:in `block in execute'
/home/gokul/root/mobme/mpassbook-ubi-mpassbook-rails/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract_adapter.rb:466:in `block in log'
/home/gokul/root/mobme/mpassbook-ubi-mpassbook-rails/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.0/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/home/gokul/root/mobme/mpassbook-ubi-mpassbook-rails/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract_adapter.rb:460:in `log'
/home/gokul/root/mobme/mpassbook-ubi-mpassbook-rails/vendor/cache/oracle-enhanced-6ca7870adaa1/lib/active_record/connection_adapters/oracle_enhanced_adapter.rb:1300:in `log'
/home/gokul/root/mobme/mpassbook-ubi-mpassbook-rails/vendor/cache/oracle-enhanced-6ca7870adaa1/lib/active_record/connection_adapters/oracle_enhanced_database_statements.rb:10:in `execute'
/home/gokul/root/mobme/mpassbook-ubi-mpassbook-rails/vendor/cache/oracle-enhanced-6ca7870adaa1/lib/active_record/connection_adapters/oracle_enhanced_schema_statements.rb:191:in `add_index'
/home/gokul/root/mobme/mpassbook-ubi-mpassbook-rails/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.0/lib/active_record/migration.rb:662:in `block in method_missing'
/home/gokul/root/mobme/mpassbook-ubi-mpassbook-rails/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.0/lib/active_record/migration.rb:632:in `block in say_with_time'
/home/gokul/root/mobme/mpassbook-ubi-mpassbook-rails/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.0/lib/active_record/migration.rb:632:in `say_with_time'
/home/gokul/root/mobme/mpassbook-ubi-mpassbook-rails/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.0/lib/active_record/migration.rb:652:in `method_missing'
/home/gokul/root/mobme/mpassbook-ubi-mpassbook-rails/db/schema.rb:38:in `block in <top (required)>'
/home/gokul/root/mobme/mpassbook-ubi-mpassbook-rails/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.0/lib/active_record/schema.rb:41:in `instance_eval'
/home/gokul/root/mobme/mpassbook-ubi-mpassbook-rails/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.0/lib/active_record/schema.rb:41:in `define'
/home/gokul/root/mobme/mpassbook-ubi-mpassbook-rails/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.0/lib/active_record/schema.rb:61:in `define'
/home/gokul/root/mobme/mpassbook-ubi-mpassbook-rails/db/schema.rb:14:in `<top (required)>'
/home/gokul/root/mobme/mpassbook-ubi-mpassbook-rails/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:268:in `load'
/home/gokul/root/mobme/mpassbook-ubi-mpassbook-rails/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:268:in `block in load'
/home/gokul/root/mobme/mpassbook-ubi-mpassbook-rails/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:240:in `load_dependency'
/home/gokul/root/mobme/mpassbook-ubi-mpassbook-rails/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:268:in `load'
/home/gokul/root/mobme/mpassbook-ubi-mpassbook-rails/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.0/lib/active_record/tasks/database_tasks.rb:218:in `load_schema_for'
/home/gokul/root/mobme/mpassbook-ubi-mpassbook-rails/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.0/lib/active_record/tasks/database_tasks.rb:235:in `block in load_schema_current'
/home/gokul/root/mobme/mpassbook-ubi-mpassbook-rails/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.0/lib/active_record/tasks/database_tasks.rb:275:in `block in each_current_configuration'
/home/gokul/root/mobme/mpassbook-ubi-mpassbook-rails/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.0/lib/active_record/tasks/database_tasks.rb:274:in `each'
/home/gokul/root/mobme/mpassbook-ubi-mpassbook-rails/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.0/lib/active_record/tasks/database_tasks.rb:274:in `each_current_configuration'
/home/gokul/root/mobme/mpassbook-ubi-mpassbook-rails/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.0/lib/active_record/tasks/database_tasks.rb:234:in `load_schema_current'
/home/gokul/root/mobme/mpassbook-ubi-mpassbook-rails/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.0/lib/active_record/railties/databases.rake:244:in `block (3 levels) in <top (required)>'
/home/gokul/root/mobme/mpassbook-ubi-mpassbook-rails/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.0/lib/active_record/railties/databases.rake:248:in `block (3 levels) in <top (required)>'
/home/gokul/root/mobme/mpassbook-ubi-mpassbook-rails/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.0/lib/active_record/railties/databases.rake:139:in `block (2 levels) in <top (required)>'
/home/gokul/root/mobme/mpassbook-ubi-mpassbook-rails/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:268:in `load'
/home/gokul/root/mobme/mpassbook-ubi-mpassbook-rails/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:268:in `block in load'
/home/gokul/root/mobme/mpassbook-ubi-mpassbook-rails/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:240:in `load_dependency'
/home/gokul/root/mobme/mpassbook-ubi-mpassbook-rails/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:268:in `load'
-e:1:in `<main>'
OCIError: ORA-02327: cannot create index on expression with datatype LOB
stmt.c:250:in oci8lib_220.so
/home/gokul/root/mobme/mpassbook-ubi-mpassbook-rails/vendor/bundle/ruby/2.2.0/gems/ruby-oci8-2.1.8/lib/oci8/cursor.rb:129:in `exec'
/home/gokul/root/mobme/mpassbook-ubi-mpassbook-rails/vendor/bundle/ruby/2.2.0/gems/ruby-oci8-2.1.8/lib/oci8/oci8.rb:278:in `exec_internal'
/home/gokul/root/mobme/mpassbook-ubi-mpassbook-rails/vendor/bundle/ruby/2.2.0/gems/ruby-oci8-2.1.8/lib/oci8/oci8.rb:269:in `exec'
/home/gokul/root/mobme/mpassbook-ubi-mpassbook-rails/vendor/cache/oracle-enhanced-6ca7870adaa1/lib/active_record/connection_adapters/oracle_enhanced_oci_connection.rb:431:in `exec'
/home/gokul/root/mobme/mpassbook-ubi-mpassbook-rails/vendor/cache/oracle-enhanced-6ca7870adaa1/lib/active_record/connection_adapters/oracle_enhanced_oci_connection.rb:90:in `exec'
/home/gokul/root/mobme/mpassbook-ubi-mpassbook-rails/vendor/cache/oracle-enhanced-6ca7870adaa1/lib/active_record/connection_adapters/oracle_enhanced_database_statements.rb:10:in `block in execute'
/home/gokul/root/mobme/mpassbook-ubi-mpassbook-rails/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract_adapter.rb:466:in `block in log'
/home/gokul/root/mobme/mpassbook-ubi-mpassbook-rails/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.0/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/home/gokul/root/mobme/mpassbook-ubi-mpassbook-rails/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract_adapter.rb:460:in `log'
/home/gokul/root/mobme/mpassbook-ubi-mpassbook-rails/vendor/cache/oracle-enhanced-6ca7870adaa1/lib/active_record/connection_adapters/oracle_enhanced_adapter.rb:1300:in `log'
/home/gokul/root/mobme/mpassbook-ubi-mpassbook-rails/vendor/cache/oracle-enhanced-6ca7870adaa1/lib/active_record/connection_adapters/oracle_enhanced_database_statements.rb:10:in `execute'
/home/gokul/root/mobme/mpassbook-ubi-mpassbook-rails/vendor/cache/oracle-enhanced-6ca7870adaa1/lib/active_record/connection_adapters/oracle_enhanced_schema_statements.rb:191:in `add_index'
/home/gokul/root/mobme/mpassbook-ubi-mpassbook-rails/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.0/lib/active_record/migration.rb:662:in `block in method_missing'
/home/gokul/root/mobme/mpassbook-ubi-mpassbook-rails/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.0/lib/active_record/migration.rb:632:in `block in say_with_time'
/home/gokul/root/mobme/mpassbook-ubi-mpassbook-rails/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.0/lib/active_record/migration.rb:632:in `say_with_time'
/home/gokul/root/mobme/mpassbook-ubi-mpassbook-rails/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.0/lib/active_record/migration.rb:652:in `method_missing'
/home/gokul/root/mobme/mpassbook-ubi-mpassbook-rails/db/schema.rb:38:in `block in <top (required)>'
/home/gokul/root/mobme/mpassbook-ubi-mpassbook-rails/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.0/lib/active_record/schema.rb:41:in `instance_eval'
/home/gokul/root/mobme/mpassbook-ubi-mpassbook-rails/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.0/lib/active_record/schema.rb:41:in `define'
/home/gokul/root/mobme/mpassbook-ubi-mpassbook-rails/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.0/lib/active_record/schema.rb:61:in `define'
/home/gokul/root/mobme/mpassbook-ubi-mpassbook-rails/db/schema.rb:14:in `<top (required)>'
/home/gokul/root/mobme/mpassbook-ubi-mpassbook-rails/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:268:in `load'
/home/gokul/root/mobme/mpassbook-ubi-mpassbook-rails/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:268:in `block in load'
/home/gokul/root/mobme/mpassbook-ubi-mpassbook-rails/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:240:in `load_dependency'
/home/gokul/root/mobme/mpassbook-ubi-mpassbook-rails/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:268:in `load'
/home/gokul/root/mobme/mpassbook-ubi-mpassbook-rails/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.0/lib/active_record/tasks/database_tasks.rb:218:in `load_schema_for'
/home/gokul/root/mobme/mpassbook-ubi-mpassbook-rails/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.0/lib/active_record/tasks/database_tasks.rb:235:in `block in load_schema_current'
/home/gokul/root/mobme/mpassbook-ubi-mpassbook-rails/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.0/lib/active_record/tasks/database_tasks.rb:275:in `block in each_current_configuration'
/home/gokul/root/mobme/mpassbook-ubi-mpassbook-rails/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.0/lib/active_record/tasks/database_tasks.rb:274:in `each'
/home/gokul/root/mobme/mpassbook-ubi-mpassbook-rails/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.0/lib/active_record/tasks/database_tasks.rb:274:in `each_current_configuration'
/home/gokul/root/mobme/mpassbook-ubi-mpassbook-rails/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.0/lib/active_record/tasks/database_tasks.rb:234:in `load_schema_current'
/home/gokul/root/mobme/mpassbook-ubi-mpassbook-rails/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.0/lib/active_record/railties/databases.rake:244:in `block (3 levels) in <top (required)>'
/home/gokul/root/mobme/mpassbook-ubi-mpassbook-rails/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.0/lib/active_record/railties/databases.rake:248:in `block (3 levels) in <top (required)>'
/home/gokul/root/mobme/mpassbook-ubi-mpassbook-rails/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.0/lib/active_record/railties/databases.rake:139:in `block (2 levels) in <top (required)>'
/home/gokul/root/mobme/mpassbook-ubi-mpassbook-rails/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:268:in `load'
/home/gokul/root/mobme/mpassbook-ubi-mpassbook-rails/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:268:in `block in load'
/home/gokul/root/mobme/mpassbook-ubi-mpassbook-rails/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:240:in `load_dependency'
/home/gokul/root/mobme/mpassbook-ubi-mpassbook-rails/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:268:in `load'
-e:1:in `<main>'
Tasks: TOP => db:schema:load
(See full trace by running task with --trace)
```

**Comment by gokulnath** [comment]
I am using oracle_enhanced adapter (https://github.com/rsim/oracle-enhanced)
